# Generated by Django 3.1.6 on 2021-03-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidsymptom',
            name='user',
            field=models.IntegerField(),
        ),
    ]
