# Generated by Django 3.1.6 on 2021-03-15 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210315_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covidsymptom',
            old_name='user',
            new_name='user_id',
        ),
    ]
