# Generated by Django 3.1.6 on 2021-03-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210315_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidsymptom',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
